const { error } = require("../../utils/response")

const get = async (req, res) => {
    try{
        // const data = 
    }catch(err){
        return error(res, err.message)
    }
}